---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: graphana-ingress
  namespace: metrics
spec:
  host: graphana.kostis.sales-dev.codefresh.io
  prefix: /
  service: graphana-grafana.metrics:80
